import React from 'react'

export default function BracketsTab() {
    return (
        <div className="">
            <div class="tournament">
            <div>
                <div>
                    <ul>
                        <li>bbb</li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <div>
                <div>
                    <ul>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
        </div>
            
        </div>
    )
}
